### PR TITLE
Added missing example command to include best-estimate file

### PR DESCRIPTION
**Pull request by Poruthoor**
Hi Louis,

I was using your script for estimating error across multiple replicas in my use case and I have a combined FEC as a best estimate. However, it felt like an example command was missing in your fullhelp.txt and python print statement for the fullhelp. This example template seems to work for me, let me know, if this is **not** the intended use case.

### CODE REVIEW

**Comment by lgsmith** [comment]
the curve-i.dat shoudl be removed from both of the example lines in both places where it was added.

Not that you did this, but since you're touching up the fullhelp changing 'where the curve-i.dat files are placeholders for the files containing the FECs' to 'where the .dat files contain the FECs.' 

Otherwise this looks fine.

**Comment by lgsmith** [comment]
Also noticed an error in the example like for the prefix flag. It currently says the output file will be called `prefix-deriv-0.asc` when the flag `--prefix example` is thrown, but it should actually be `example-deriv-0.asc`, I believe.

**Comment by Poruthoor** [comment]
> Also noticed an error in the example like for the prefix flag. It currently says the output file will be called `prefix-deriv-0.asc` when the flag `--prefix example` is thrown, but it should actually be `example-deriv-0.asc`, I believe.

Isn't the default prefix `dstats`?

**Comment by Poruthoor** [comment]
> the curve-i.dat shoudl be removed from both of the example lines in both places where it was added.
> 
> Not that you did this, but since you're touching up the fullhelp changing 'where the curve-i.dat files are placeholders for the files containing the FECs' to 'where the .dat files contain the FECs.'
> 
> Otherwise this looks fine.

This is done

**Comment by lgsmith** [comment]
> > Also noticed an error in the example like for the prefix flag. It currently says the output file will be called `prefix-deriv-0.asc` when the flag `--prefix example` is thrown, but it should actually be `example-deriv-0.asc`, I believe.
> 
> Isn't the default prefix `dstats`?

Oh yeah the diff was just displaying something in a way that made it seem like it was an error when it wasn't in the web viewer. Looking at the original text, everything should be fine there. This works. Thanks.

**Pull request merged**
